import {
    IS_PHONE_X,
    NAVIGATION_BAR_HEIGHT,
    TAB_BAR_HEIGHT,
    THEME_COLOR,
    TEXT_MAIN_COLOR,
    SCREEN_WIDTH,
    SCREEN_HEIGHT
} from './Configure';

export {
    IS_PHONE_X,
    NAVIGATION_BAR_HEIGHT,
    TAB_BAR_HEIGHT,
    THEME_COLOR,
    TEXT_MAIN_COLOR,
    SCREEN_WIDTH,
    SCREEN_HEIGHT
}